// src/components/SiteHeader.svelte
<script>
  export let segment;
</script>

<style lang="less">
  header {
    nav {
      display: flex;
      flex-direction: row;
    }
    a {
      padding: 16px 24px;
      display: block;

      &.selected {
        /* border: 1px solid red; */
        color: orange;
      }
    }
  }
</style>

<header>
  <nav>
    <a class:selected={segment === undefined} href="/">Home</a>
    <a class:selected={segment === 'about.html'} href="/about.html">About</a>
  </nav>
</header>

// src/components/SiteHeader.tsx
import Link from 'next/link';

const SiteHeader: React.FC<{}> = () => {
    return (
        <header className="site-header">
            <div className="flex items-center flex-wrap bg-orange-200">
                <nav className="w-full max-w-screen-xl mx-auto">
                    <Link href="/">
                        <a className="inline-block p-6">Home</a>
                    </Link>
                    <Link href="/about.html">
                        <a className="inline-block p-6">About me</a>
                    </Link>
                </nav>
            </div>
        </header>
    );
};

export default SiteHeader;
